<?php
// $Id$

/**
 * @file
 * TODO: Enter file description here.
 */

/**
 * Implementation of hook_menu().
 */
function teacher_menu() {
  $items['teacher'] = array(
    'title' => '教师平台',
    'page callback' => 'views_embed_view',
    'page arguments' => array('lessonList', 'default'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
