<?php
// $Id$

/**
 * @file
 * Teacher Module
 */

/**
 * Implementation of hook_menu().
 */
function student_menu() {
  $items['student'] = array(
    'title' => '学生平台',
  	'description' => '学习课程与实验、查看通知、完成作业与测试',
    'page callback' => 'student_task_list',
		'access arguments' => array('access content'), 
    'type' => MENU_NORMAL_ITEM,
  );
  $items['student/notices'] = array(
    'title' => '查看通知',
 		'page callback' => 'drupal_get_form',
    'page arguments' => array('student_notices'),
  	'access arguments' => array('access student pages'), 
    'type' => MENU_CALLBACK,
  );
  $items['student/lessons'] = array(
    'title' => '课程与实验',
 		'page callback' => 'drupal_get_form',
    'page arguments' => array('student_lessons'),
  	'access arguments' => array('access student pages'), 
    'type' => MENU_CALLBACK,
  );
  $items['student/tests'] = array(
    'title' => '作业',
 		'page callback' => 'drupal_get_form',
    'page arguments' => array('student_tests'),
  	'access arguments' => array('access student pages'), 
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function student_perm() {
	return array('access student pages');
}

function student_theme() {
	return array(
	'student_nodes_list' => array(
      'arguments' => array('form' => NULL),
    ),
	);
}

function student_task_list() {
	$menu_items = array();
  $menu_items['通知'] = array(
  	'查看通知', 
  	array(
  		l('查看通知', 'student/notices'), 
  	),
  );
  $menu_items['课程与实验'] = array(
    '课程与实验学习、提问与答疑', 
  	array(
  		l('课程与实验列表', 'student/lessons'), 
  	),
  );
  $menu_items['作业管理'] = array(
    '完成作业、查看作业反馈', 
  	array(
  		l('作业列表', 'student/tests'), 
  	),
  );
  return theme('teacher_task_list', $menu_items);
}

function student_help($path, $arg) {
  global $base_url;
  switch ($path) {
    case 'student':
    	$output = '<p>'.'学习课程与实验、查看通知、完成作业与测试'.'<p>';
    	return $output;
  }
}

function student_notices() {
	global $user;
	if (!empty($user->class)) {
  	$result = pager_query('SELECT n.*, u.name FROM {node} n '.' INNER JOIN {users} u ON n.uid = u.uid '.' INNER JOIN {content_field_class} nc ON n.nid = nc.nid '.' WHERE n.type = "notice" AND n.status = 1 AND nc.field_class_value = '.$user->class.' ORDER BY n.changed DESC');
	}
  $destination = drupal_get_destination();
  $nodes = array();
  while ($node = db_fetch_object($result)) {
    $nodes[$node->nid] = '';
    $options = array();
    $form['title'][$node->nid] = array('#value' => l($node->title, 'node/'. $node->nid, $options));
    $form['username'][$node->nid] = array('#value' => $node->name);
    $form['date'][$node->nid] = array('#value' => format_date($node->changed));
  }
  $form['pager'] = array('#value' => theme('pager', NULL, 50, 0));
  $form['#theme'] = 'student_nodes_list';
  return $form;
}

function student_lessons() {
	global $user;
	if (!empty($user->class)) {
  	$result = pager_query('SELECT n.*, u.name FROM {node} n '.' INNER JOIN {users} u ON n.uid = u.uid '.' WHERE n.type = "lesson" AND n.status = 1 ORDER BY n.changed DESC');
	}
  $destination = drupal_get_destination();
  $nodes = array();
  while ($node = db_fetch_object($result)) {
    $nodes[$node->nid] = '';
    $options = array();
    $form['title'][$node->nid] = array('#value' => l($node->title, 'node/'. $node->nid, $options));
    $form['username'][$node->nid] = array('#value' => $node->name);
    $form['date'][$node->nid] = array('#value' => format_date($node->changed));
  }
  $form['pager'] = array('#value' => theme('pager', NULL, 50, 0));
  $form['#theme'] = 'student_nodes_list';
  return $form;
}

function student_tests() {
	global $user;
	if (!empty($user->class)) {
  	$result = pager_query('SELECT n.*, u.name FROM {node} n '.' INNER JOIN {users} u ON n.uid = u.uid '.' INNER JOIN {content_field_class} nc ON n.nid = nc.nid '.' WHERE n.type = "test" AND n.status = 1 AND nc.field_class_value = '.$user->class.' ORDER BY n.changed DESC');
	}
  $destination = drupal_get_destination();
  $nodes = array();
  while ($node = db_fetch_object($result)) {
    $nodes[$node->nid] = '';
    $options = array();
    $form['title'][$node->nid] = array('#value' => l($node->title, 'node/'. $node->nid, $options));
    $form['username'][$node->nid] = array('#value' => $node->name);
    $form['date'][$node->nid] = array('#value' => format_date($node->changed));
  }
  $form['pager'] = array('#value' => theme('pager', NULL, 50, 0));
  $form['#theme'] = 'student_nodes_list';
  return $form;
}

function theme_student_nodes_list($form) {
	// If there are rows in this form, then $form['title'] contains a list of
  // the title form elements.
  $has_posts = isset($form['title']) && is_array($form['title']);
  $select_header = $has_posts ? theme('table_select_header_cell') : '';
  $header = array(t('Title'), t('Author'), t('Date'));
  $output = '';
  $output .= drupal_render($form['options']);
  if ($has_posts) {
    foreach (element_children($form['title']) as $key) {
      $row = array();
      //$row[] = drupal_render($form['nodes'][$key]);
      $row[] = drupal_render($form['title'][$key]);
      $row[] = drupal_render($form['username'][$key]);
      $row[] = drupal_render($form['date'][$key]);
      $rows[] = $row;
    }

  }
  else {
    $rows[] = array(array('data' => t('No posts available.'), 'colspan' => '6'));
  }

  $output .= theme('table', $header, $rows);
  if ($form['pager']['#value']) {
    $output .= drupal_render($form['pager']);
  }

  $output .= drupal_render($form);

  return $output;
}